### ISSUE TITLE
trakts init [Installation] 

### ISSUE THREAD

**Issue by MFKDGAF** [iamkroot/trakt-scrobbler#224]
### System Info
* Operating system and version: [eg: Windows 10, Linux Manjaro KDE]: Windows Server 2022 Standard
* Media Player and version: [eg: VLC v3.0.16, Plex v1.24.0.4930]: Plex v1.29.2.6354
* Python version: [eg: 3.9]: 3.11

### Description
Briefly describe the error you are facing

trakts init

### Command line output

```
 OSError

  [WinError -2147024809] The parameter is incorrect

  at .local\pipx\venvs\trakt-scrobbler\Lib\site-packages\desktop_notifier\winrt.py:74 in __init__
       70│     ) -> None:
       71│         super().__init__(app_name, app_icon, notification_limit)
       72│         self._appid = CoreApplication.get_id()
       73│         self.manager = ToastNotificationManager.get_default()
    →  74│         self.notifier = self.manager.create_toast_notifier(self._appid)
       75│
       76│         # BackgroundExecutionManager.remove_access(self._appid)
       77│         # CoreApplication.add_background_activated(self._on_background_activated)
       78│
```

### Log file

<details>
  <summary>Click to see log contents</summary>  
<p>

```
(replace these lines) *PASTE LOG FILE CONTENTS HERE*
  Command: "trakts log open" or "trakts log path" or
  see [FAQ](https://github.com/iamkroot/trakt-scrobbler/wiki/FAQs#where-is-the-log-fileother-data-stored).
```
</p>
</details>

**Comment by iamkroot** [comment]
Sadly, this is an upstream bug https://github.com/samschott/desktop-notifier/issues/41 for Windows.

For now, you can install an older version of the app-
1. `pipx uninstall trakt-scrobbler`
2. `pix install trakt-scrobbler==1.5.0`
3. `trakts init`

Once the upstream bug is fixed, I'll release a new version of the app so that you can update. Will keep this open till then.

**Comment by iamkroot** [comment]
I've released `v1.6.1-beta1` with the fix included from upstream. Please give it a try-
1. `pipx uninstall trakt-scrobbler`
2. `pix install trakt-scrobbler==1.6.1b1`
3. `trakts init`

**Comment by Sooleawa** [comment]
> I've released `v1.6.1-beta1` with the fix included from upstream. Please give it a try-
> 
> 1. `pipx uninstall trakt-scrobbler`
> 2. `pix install trakt-scrobbler==1.6.1b1`
> 3. `trakts init`

pipx uninstall trakt-scrobbler
uninstalled trakt-scrobbler! ✨ 🌟 ✨

pipx install trakt-scrobbler==1.6.1b1
  installed package trakt-scrobbler 1.6.1b1, installed using Python 3.11.0
  These apps are now globally available
    - trakts.exe
done! ✨ 🌟 ✨

trakts init
This will guide you through the setup of the scrobbler.
If you wish to quit at any point, press Ctrl+C or Cmd+C

  OSError

  [WinError -2147024809] The parameter is incorrect

  at .local\pipx\venvs\trakt-scrobbler\Lib\site-packages\desktop_notifier\winrt.py:74 in __init__
       70│     ) -> None:
       71│         super().__init__(app_name, app_icon, notification_limit)
       72│         self._appid = CoreApplication.get_id()
       73│         self.manager = ToastNotificationManager.get_default()
    →  74│         self.notifier = self.manager.create_toast_notifier(self._appid)
       75│
       76│         # BackgroundExecutionManager.remove_access(self._appid)
       77│         # CoreApplication.add_background_activated(self._on_background_activated)
       78│

**Comment by iamkroot** [comment]
Yep, looks like the upstream bug is still present. Please fall back to the older version for now.

**Comment by iamkroot** [comment]
This should be resolved in `v1.6.3`. Please update.
