### ISSUE TITLE
Python 3.12 RC from winsows store broke trakts

### ISSUE THREAD

**Issue by panaris** [iamkroot/trakt-scrobbler#257]
Installation through pip works fine though.
![erCp9sB](https://github.com/iamkroot/trakt-scrobbler/assets/20076245/3207fad5-bc77-4be8-9eff-5e12bbbb7d8d)

**Comment by iamkroot** [comment]
How exactly did you install `trakt-scrobbler`? With `pipx` this shouldn't happen

**Comment by panaris** [comment]
I removed old python version. Installed lates windows store version. Removed pipx and the folder $home/.local/pipx. Then tried to install trakts through pipx. Everything went well but init failed. Then tried to uninstall via pipx and install though pip and same thing happened.

**Comment by bulletproof2k** [comment]
How to update and which version of Plexapi are you using now?

**Comment by iamkroot** [comment]
> How to update and which version of Plexapi are you using now?

@bulletproof2k the current thread is about Python 3.12, and not a new version of trakt scrobbler. There haven't been any recent changes to the plex api usage in here. So if you're facing problems, please raise an issue (or if you already created it and I forgot, add a bump comment to it)

**Comment by bulletproof2k** [comment]
No problem, thanks for the quick response 👍

**Comment by iamkroot** [comment]
@panaris Thanks for the bug report. This was a bug in an upstream dependency https://github.com/Diaoul/babelfish/issues/46 (it uses a deprecated module which broke in Python3.12). I have pushed a fix for this, and it should work in Python3.12 now.
Install from branch:
1. Stop the scrobbler with `trakts stop`
2. Run `pipx install --force --pip-args='--force-reinstall' git+https://github.com/iamkroot/trakt-scrobbler.git@master`
3. Start scrobbler with `trakts start`

(Or, wait for a new version)

**Comment by panaris** [comment]
https://bit.ly/3QbHbdD

with the new push

**Comment by iamkroot** [comment]
That's weird, I thought I already fixed it... Could you please paste the output of `trakts init -vvv`

**Comment by MarsAgainstVenus** [comment]
So what is the fix for this? Trying to install it now and receiving the same error.

**Comment by MarsAgainstVenus** [comment]
> So what is the fix for this? Trying to install it now and receiving the same error.

Never mind. This did work for me:

`pipx install --force --pip-args='--force-reinstall' git+https://github.com/iamkroot/trakt-scrobbler.git@master`

Just a heads up that this is still occurring with fresh installs.

**Comment by iamkroot** [comment]
@MarsAgainstVenus are installing from the master as shown [here](https://github.com/iamkroot/trakt-scrobbler/issues/257#issuecomment-1752176431)? There is no stable release with the fix yet.

**Comment by DoncanC** [comment]
I followed [this](https://github.com/iamkroot/trakt-scrobbler/issues/257#issuecomment-1752176431) but I get this error

`ERROR: Invalid requirement: "'--force-reinstall'"
Cannot determine package name from spec 'git+https://github.com/iamkroot/trakt-scrobbler.git@master'. Check package
spec for errors.`

:'D

**Comment by DoncanC** [comment]
I followed [this](https://github.com/iamkroot/trakt-scrobbler/issues/257#issuecomment-1752176431) but I get this error:

ERROR: Invalid requirement: "'--force-reinstall'" Cannot determine package name from spec 'git+https://github.com/iamkroot/trakt-scrobbler.git@master'. Check package spec for errors.

I'm a beginner, so I apologize for knowing very little.
:'D

**Comment by iamkroot** [comment]
@DoncanC try https://github.com/iamkroot/trakt-scrobbler/issues/257#issuecomment-1887917122

**Comment by DoncanC** [comment]
> @DoncanC try [#257 (comment)](https://github.com/iamkroot/trakt-scrobbler/issues/257#issuecomment-1887917122)

Yes but the error is the same
`This will guide you through the setup of the scrobbler.
If you wish to quit at any point, press Ctrl+C or Cmd+C

  AttributeError

  module 'pkgutil' has no attribute 'ImpImporter'

  at AppData\Local\Programs\Python\Python312\Lib\site-packages\pkg_resources\__init__.py:2191 in <module>
      2187│     dist_groups = map(find_distributions, resolved_paths)
      2188│     return next(dist_groups, ())
      2189│
      2190│
    → 2191│ register_finder(pkgutil.ImpImporter, find_on_path)
      2192│
      2193│ if hasattr(importlib_machinery, 'FileFinder'):
      2194│     register_finder(importlib_machinery.FileFinder, find_on_path)
      2195│`

:/

**Comment by JWWolstenholme** [comment]
> That's weird, I thought I already fixed it... Could you please paste the output of `trakts init -vvv`

Since OP never responded to you and since I'm experiencing the same problem with Python `3.12.4` (installed via python's "full installer") here's my output from `trakts init -vvv`:

<details>
  <summary>Expand</summary>

  ```cmd
C:\Users\redacted>trakts init -vvv
This will guide you through the setup of the scrobbler.
If you wish to quit at any point, press Ctrl+C or Cmd+C

  Stack trace:

  9  pipx\venvs\trakt-scrobbler\Lib\site-packages\clikit\console_application.py:131 in run
      129│             parsed_args = resolved_command.args
      130│
    → 131│             status_code = command.handle(parsed_args, io)
      132│         except KeyboardInterrupt:
      133│             status_code = 1

  8  pipx\venvs\trakt-scrobbler\Lib\site-packages\clikit\api\command\command.py:120 in handle
      118│     def handle(self, args, io):  # type: (Args, IO) -> int
      119│         try:
    → 120│             status_code = self._do_handle(args, io)
      121│         except KeyboardInterrupt:
      122│             if io.is_debug():

  7  pipx\venvs\trakt-scrobbler\Lib\site-packages\clikit\api\command\command.py:171 in _do_handle
      169│         handler_method = self._config.handler_method
      170│
    → 171│         return getattr(handler, handler_method)(args, io, self)
      172│
      173│     def __repr__(self):  # type: () -> str

  6  pipx\venvs\trakt-scrobbler\Lib\site-packages\cleo\commands\command.py:92 in wrap_handle
       90│         self._command = command
       91│
    →  92│         return self.handle()
       93│
       94│     def handle(self):  # type: () -> Optional[int]

  5  pipx\venvs\trakt-scrobbler\Lib\site-packages\trakt_scrobbler\commands\init.py:24 in handle
      22│         self.comment("This will guide you through the setup of the scrobbler.")
      23│         self.info("If you wish to quit at any point, press Ctrl+C or Cmd+C")
    → 24│         from trakt_scrobbler.player_monitors import collect_monitors
      25│
      26│         monitors = {Mon for Mon in collect_monitors() if isinstance(Mon.name, str)}

  4  pipx\venvs\trakt-scrobbler\Lib\site-packages\trakt_scrobbler\player_monitors\__init__.py:4 in <module>
       2│ from pathlib import Path
       3│ from importlib import import_module
    →  4│ from .monitor import Monitor
       5│
       6│

  3  pipx\venvs\trakt-scrobbler\Lib\site-packages\trakt_scrobbler\player_monitors\monitor.py:9 in <module>
        7│ from trakt_scrobbler import config, logger
        8│ from trakt_scrobbler.file_info import get_media_info
    →   9│ from trakt_scrobbler.notifier import notify
       10│ from trakt_scrobbler.utils import AutoloadError, ResumableTimer
       11│

  2  pipx\venvs\trakt-scrobbler\Lib\site-packages\trakt_scrobbler\notifier.py:104 in <module>
      102│
      103│ else:
    → 104│     from win10toast import ToastNotifier
      105│     toaster = ToastNotifier()
      106│

  1  pipx\venvs\trakt-scrobbler\Lib\site-packages\win10toast\__init__.py:15 in <module>
       13│ from os import path
       14│ from time import sleep
    →  15│ from pkg_resources import Requirement
       16│ from pkg_resources import resource_filename
       17│

  AttributeError

  module 'pkgutil' has no attribute 'ImpImporter'

  at pipx\venvs\trakt-scrobbler\Lib\site-packages\pkg_resources\__init__.py:2191 in <module>
      2187│     dist_groups = map(find_distributions, resolved_paths)
      2188│     return next(dist_groups, ())
      2189│
      2190│
    → 2191│ register_finder(pkgutil.ImpImporter, find_on_path)
      2192│
      2193│ if hasattr(importlib_machinery, 'FileFinder'):
      2194│     register_finder(importlib_machinery.FileFinder, find_on_path)
      2195│
  ```
</details>

In the meantime, I'll use one of the solutions above. Failing that I'll just downgrade python.

I doubt this is relevant to this issue but might be worth mentioning that `python` in my `PATH` is set to a bash script that runs `py` instead, which at the time of writing just defaults to running the version mentioned above. Should be no difference.

**Comment by iamkroot** [comment]
@JWWolstenholme what version of the scrobbler are you running (output of `trakts -V`)? This should have been fixed in the latest beta (`v1.7.0-beta1`)

Install beta version:
1. Stop the scrobbler with `trakts stop`
2. `pipx uninstall trakt-scrobbler`
3. Run `pipx install --pip-args='--pre' trakt-scrobbler==1.7.0b1`
4. Start scrobbler with `trakts start`

**Comment by JWWolstenholme** [comment]
@iamkroot I was running `1.6.3` as I didn't go out of my way to specify any version.
I've tested out `v1.7.0-beta1` on python `3.12.4` and can confirm that works. Thanks for the help!
Note that I had to correct step 3. in your instructions to `pipx install --pip-args=--pre trakt-scrobbler==1.7.0b1` (something to do with `pip-args` starting with `--` I think?).

**Comment by Dragoonstorm1** [comment]
Yep this is still happening to me, the stable and beta branches didnt work, same error. But the `pipx install --force --pip-args='--force-reinstall' git+https://github.com/iamkroot/trakt-scrobbler.git@master` command did the trick.

**Comment by lowbit** [comment]
`trakts init
This will guide you through the setup of the scrobbler.
If you wish to quit at any point, press Ctrl+C or Cmd+C

  AttributeError

  module 'pkgutil' has no attribute 'ImpImporter'

  at pipx\venvs\trakt-scrobbler\Lib\site-packages\pkg_resources\__init__.py:2191 in <module>
      2187│     dist_groups = map(find_distributions, resolved_paths)
      2188│     return next(dist_groups, ())
      2189│
      2190│
    → 2191│ register_finder(pkgutil.ImpImporter, find_on_path)
      2192│
      2193│ if hasattr(importlib_machinery, 'FileFinder'):
      2194│     register_finder(importlib_machinery.FileFinder, find_on_path)
      2195│`
