### ISSUE TITLE
[BUG] Double scrobble at end of playback in MPC

### ISSUE THREAD

**Issue by iamkroot** [iamkroot/trakt-scrobbler#8]
> Second issue, this one is really minor, if I let MPC reach the very very ending [like so](https://i.imgur.com/duofwmL.png) the episode will somehow scrobble [twice](https://i.imgur.com/P820BSW.png), notice that it seems that it did both at the same time but in reality the second one takes about 20 minutes to appear.

_Originally posted by @cyatek in https://github.com/iamkroot/trakt-scrobbler/issues/3#issuecomment-501876944_

**Comment by iamkroot** [comment]
Seems to be happening as MPC pauses the file at the last second, instead of stopping, which is considered to be a 'STOP' by trakt.

**Comment by iamkroot** [comment]
@cyatek I've pushed some fixes for this. Could you please update, and check if its working properly?

**Comment by cyatek** [comment]
Looks like it's still happening
https://i.imgur.com/bMbC9ip.png

**Log file**
<details><summary>Click to see log contents</summary>
<p>

```
2019-06-16 15:58:21,726 - DEBUG - mpchc - file_info - Filepath E:\TV\Norm.Macdonald.Has.a.Show.S01.COMPLETE.720p.NF.WEBRip.DDP2.0.x264-monkee[TGx]\Norm.Macdonald.Has.a.Show.S01E05.Jane.Fonda.720p.NF.WEB-DL.DDP2.0.x264-monkee.mkv
2019-06-16 15:58:21,727 - DEBUG - mpchc - file_info - Trying to match custom regex.
2019-06-16 15:58:21,727 - DEBUG - mpchc - file_info - No regex matches for E:/TV/Norm.Macdonald.Has.a.Show.S01.COMPLETE.720p.NF.WEBRip.DDP2.0.x264-monkee[TGx]/Norm.Macdonald.Has.a.Show.S01E05.Jane.Fonda.720p.NF.WEB-DL.DDP2.0.x264-monkee.mkv
2019-06-16 15:58:21,728 - DEBUG - mpchc - file_info - Using guessit module to match.
2019-06-16 15:58:22,248 - DEBUG - mpchc - file_info - MatchesDict([('title', 'Norm Macdonald Has a Show'), ('season', 1), ('other', ['Complete', 'Rip']), ('screen_size', '720p'), ('streaming_service', 'Netflix'), ('source', 'Web'), ('audio_codec', 'Dolby Digital Plus'), ('audio_channels', '2.0'), ('video_codec', 'H.264'), ('episode', 5), ('episode_title', 'Jane Fonda'), ('release_group', 'monkee'), ('container', 'mkv'), ('mimetype', 'video/x-matroska'), ('type', 'episode')])
2019-06-16 15:58:22,249 - DEBUG - scrobbler - trakt_interface - Searching cache.
2019-06-16 15:58:22,249 - DEBUG - scrobbler - trakt_interface - {'show': {'ids': {'trakt': 135426}}, 'episode': {'season': 1, 'number': 5}}
2019-06-16 15:58:22,528 - INFO - scrobbler - scrobbler - Scrobble start successful.
2019-06-16 16:26:13,038 - DEBUG - scrobbler - trakt_interface - {'show': {'ids': {'trakt': 135426}}, 'episode': {'season': 1, 'number': 5}}
2019-06-16 16:26:13,363 - INFO - scrobbler - scrobbler - Scrobble stop successful.
2019-06-16 16:26:24,042 - INFO - mpchc - monitor - Unable to connect to mpchc. Ensure that the web interface is running.
2019-06-16 16:26:24,042 - DEBUG - scrobbler - trakt_interface - {'show': {'ids': {'trakt': 135426}}, 'episode': {'season': 1, 'number': 5}}
2019-06-16 16:26:24,222 - WARNING - scrobbler - scrobbler - Scrobble unsuccessful. Will try again later.
2019-06-16 16:26:34,047 - DEBUG - mpchc - file_info - Filepath E:\TV\Norm.Macdonald.Has.a.Show.S01.COMPLETE.720p.NF.WEBRip.DDP2.0.x264-monkee[TGx]\Norm.Macdonald.Has.a.Show.S01E06.Chevy.Chase.720p.NF.WEB-DL.DDP2.0.x264-monkee.mkv
2019-06-16 16:26:34,047 - DEBUG - mpchc - file_info - Trying to match custom regex.
2019-06-16 16:26:34,047 - DEBUG - mpchc - file_info - No regex matches for E:/TV/Norm.Macdonald.Has.a.Show.S01.COMPLETE.720p.NF.WEBRip.DDP2.0.x264-monkee[TGx]/Norm.Macdonald.Has.a.Show.S01E06.Chevy.Chase.720p.NF.WEB-DL.DDP2.0.x264-monkee.mkv
2019-06-16 16:26:34,047 - DEBUG - mpchc - file_info - Using guessit module to match.
2019-06-16 16:26:34,140 - DEBUG - mpchc - file_info - MatchesDict([('title', 'Norm Macdonald Has a Show'), ('season', 1), ('other', ['Complete', 'Rip']), ('screen_size', '720p'), ('streaming_service', 'Netflix'), ('source', 'Web'), ('audio_codec', 'Dolby Digital Plus'), ('audio_channels', '2.0'), ('video_codec', 'H.264'), ('episode', 6), ('episode_title', 'Chevy Chase'), ('release_group', 'monkee'), ('container', 'mkv'), ('mimetype', 'video/x-matroska'), ('type', 'episode')])
2019-06-16 16:26:34,141 - DEBUG - scrobbler - trakt_interface - {'show': {'ids': {'trakt': 135426}}, 'episode': {'season': 1, 'number': 6}}
2019-06-16 16:26:34,398 - INFO - scrobbler - scrobbler - Scrobble start successful.
2019-06-16 16:26:34,399 - DEBUG - scrobbler - scrobbler - Adding item to history {'state': 0, 'progress': 100.0, 'media_info': {'type': 'episode', 'title': 'Norm Macdonald Has a Show', 'season': 1, 'episode': 5}, 'updated_at': 1560698773.03842}
2019-06-16 16:26:34,707 - INFO - scrobbler - scrobbler - Successfully added media to history.
2019-06-16 16:56:34,970 - DEBUG - scrobbler - trakt_interface - {'show': {'ids': {'trakt': 135426}}, 'episode': {'season': 1, 'number': 6}}
2019-06-16 16:56:35,347 - INFO - scrobbler - scrobbler - Scrobble stop successful.
2019-06-16 16:56:45,974 - INFO - mpchc - monitor - Unable to connect to mpchc. Ensure that the web interface is running.
2019-06-16 16:56:45,974 - DEBUG - scrobbler - trakt_interface - {'show': {'ids': {'trakt': 135426}}, 'episode': {'season': 1, 'number': 6}}
2019-06-16 16:56:46,159 - WARNING - scrobbler - scrobbler - Scrobble unsuccessful. Will try again later.

```
</p>
</details>

**Comment by iamkroot** [comment]
Hmm looks like its a problem carried over from before the fix. Do one thing, delete the `watched_cache.json` file once (you'll have to kill pythonw.exe first, and reboot later).

**Comment by GiacomoLaw** [comment]
Get this too, using VLC. Would the above fix it?

Thanks for the great tool!

**Comment by iamkroot** [comment]
Found the bug :) Should be fixed in the latest commit.

**Comment by GiacomoLaw** [comment]
Awesome, thanks so much! Stupid question, but how should I go about updating?
